name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py37_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py37_0
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.1=anacondar_1
  - alabaster=0.7.12=py_0
  - alembic=1.2.1=py_0
  - anaconda=custom=py37_1
  - anaconda-client=1.7.2=py_0
  - anaconda-navigator=1.9.7=py37_0
  - anaconda-project=0.8.3=py_0
  - asn1crypto=0.24.0=py37_1003
  - astroid=2.3.1=py37_0
  - astropy=3.2.1=py37h516909a_0
  - async_generator=1.10=py_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.2.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.5=py_1
  - backports.os=0.1.1=py37_1001
  - backports.shutil_get_terminal_size=1.0.0=py_3
  - backports.tempfile=1.0=py_0
  - backports.weakref=1.0.post1=py37_1000
  - beautifulsoup4=4.8.0=py37_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - bitarray=1.0.1=py37h516909a_0
  - bkcharts=0.2=py37_0
  - blas=2.12=openblas
  - bleach=3.1.0=py_0
  - blinker=1.4=py_1
  - blosc=1.17.0=he1b5a44_1
  - bokeh=1.3.4=py37_0
  - boto=2.49.0=py_0
  - bottleneck=1.2.1=py37h3010b51_1001
  - bqplot=0.11.8=py_0
  - bwidget=1.9.11=0
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.9.11=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.9.11=py37_0
  - certipy=0.1.3=py_0
  - cffi=1.12.3=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - cloudpickle=1.2.2=py_0
  - clyent=1.2.2=py_1
  - colorama=0.4.1=py_0
  - conda=4.7.12=py37_0
  - conda-build=3.18.9=py37_3
  - conda-env=2.6.0=1
  - conda-package-handling=1.6.0=py37h516909a_0
  - conda-verify=3.4.2=py_1
  - configurable-http-proxy=4.1.0=node11_1
  - contextlib2=0.6.0=py_0
  - cryptography=2.7=py37h72c5cf5_0
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_1
  - cython=0.29.13=py37he1b5a44_0
  - cytoolz=0.10.0=py37h516909a_0
  - dask=2.5.0=py_0
  - dask-core=2.5.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.5.1=py_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_1000
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.6=he6710b0_0
  - fastcache=1.1.0=py37h516909a_0
  - filelock=3.0.10=py_0
  - flask=1.1.1=py_1
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - fsspec=0.5.1=py_0
  - future=0.17.1=py37_1000
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - get_terminal_size=1.0.0=haa9412d_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - gevent=1.4.0=py37h14c3975_0
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_9
  - glib=2.58.3=h6f030ca_1002
  - glob2=0.7=py_0
  - gmp=6.1.2=hf484d3e_1000
  - gmpy2=2.1.0b1=py37h04dde30_0
  - graphite2=1.3.13=hf484d3e_1000
  - greenlet=0.4.15=py37h516909a_0
  - gsl=2.5=h294904e_1
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - h5py=2.9.0=py37h7918eee_0
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=py_0
  - html5lib=1.0.1=py_0
  - icu=64.2=he1b5a44_1
  - idna=2.8=py37_1000
  - imageio=2.5.0=py37_0
  - imagesize=1.1.0=py_0
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=243
  - ipydatawidgets=4.0.1=py_0
  - ipykernel=5.1.2=py37h5ca1d4c_0
  - ipyscales=0.3.0=py_0
  - ipython=7.8.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py_0
  - jbig=2.1=h14c3975_2001
  - jdcal=1.4.1=py_0
  - jedi=0.15.1=py37_0
  - jeepney=0.4.1=py_0
  - jinja2=2.10.1=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.8.5=py_0
  - jsoncpp=1.8.4=hfd86e86_0
  - jsonschema=3.0.2=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py37_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - jupyter_server=0.1.1=py37_0
  - jupyterhub=1.0.0=py37_0
  - jupyterlab=1.1.4=pyhf63ae98_0
  - jupyterlab_pygments=0.1.0=py_0
  - jupyterlab_server=1.0.6=py_0
  - k3d=2.7.0=py_0
  - keyring=19.2.0=py37_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - lazy-object-proxy=1.4.2=py37h516909a_0
  - libarchive=3.3.3=hb44662c_1005
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libcurl=7.65.3=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=12_openblas
  - liblapacke=3.8.0=12_openblas
  - liblief=0.9.0=hf8a498c_1
  - libnetcdf=4.6.1=h11d0813_2
  - libogg=1.3.2=h7b6447c_0
  - libopenblas=0.3.7=h6e990d7_1
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtheora=1.1.1=h5ab3b9f_1
  - libtiff=4.0.10=h57b8799_1003
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libvorbis=1.3.6=h7b6447c_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_5
  - libxslt=1.1.33=h31b3aaa_0
  - llvmlite=0.29.0=py37hfd453ef_1
  - locket=0.2.0=py_2
  - lxml=4.4.1=py37h7ec2d77_0
  - lz4-c=1.8.3=he1b5a44_1001
  - lzo=2.10=h14c3975_1000
  - make=4.2.1=h14c3975_2004
  - mako=1.1.0=py_0
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37he7580a8_1
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37h14c3975_1000
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37h516909a_0
  - mkl_fft=1.0.14=py37h516909a_1
  - mkl_random=1.1.0=py37hb3f55d8_0
  - mock=3.0.5=py37_0
  - more-itertools=7.2.0=py_0
  - mpc=1.1.0=hb20f59a_1006
  - mpfr=4.0.2=he80fd80_0
  - mpmath=1.1.0=py_0
  - msgpack-python=0.6.2=py37hc9558a2_0
  - multipledispatch=0.6.0=py_0
  - navigator-updater=0.2.1=py37_0
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.3=py_0
  - nltk=3.4.4=py_0
  - nodejs=11.14.0=he1b5a44_1
  - nose=1.3.7=py37_1002
  - notebook=6.0.1=py37_0
  - numba=0.45.1=py37hb3f55d8_0
  - numexpr=2.7.0=py37hb3f55d8_0
  - numpy=1.17.2=py37h95a1406_0
  - numpy-base=1.17.2=py37h2f8d375_0
  - numpydoc=0.9.1=py_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py_0
  - openpyxl=3.0.0=py_0
  - openssl=1.1.1c=h516909a_0
  - packaging=19.2=py_0
  - pamela=1.0.0=py_0
  - pandas=0.25.1=py37hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=ha030887_1
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - patchelf=0.10=he1b5a44_0
  - path.py=12.0.1=py_0
  - pathlib2=2.3.5=py37_0
  - patsy=0.5.1=py_0
  - pcre=8.41=hf484d3e_1003
  - pep8=1.7.1=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=6.1.0=py37h6b7be26_1
  - pip=19.2.3=py37_0
  - pixman=0.38.0=h516909a_1003
  - pkginfo=1.5.0.1=py_0
  - pluggy=0.13.0=py37_0
  - ply=3.11=py_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - psutil=5.6.3=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.8.0=py_0
  - py-lief=0.9.0=py37he1b5a44_1
  - pycodestyle=2.5.0=py_0
  - pycosat=0.6.3=py37h14c3975_1001
  - pycparser=2.19=py37_1
  - pycrypto=2.6.1=py37h516909a_1003
  - pycurl=7.43.0.2=py37h16ce93b_1
  - pyflakes=2.1.1=py_0
  - pygments=2.4.2=py_0
  - pyjwt=1.7.1=py_0
  - pylint=2.4.2=py37_0
  - pyodbc=4.0.27=py37he1b5a44_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pyrsistent=0.15.4=py37h516909a_0
  - pysocks=1.7.1=py37_0
  - pytables=3.5.2=py37h71ec239_1
  - pytest=5.2.0=py37_0
  - pytest-arraydiff=0.3=py_0
  - pytest-astropy=0.5.0=py_0
  - pytest-doctestplus=0.4.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.1=py_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.0=py_0
  - python-editor=1.0.4=py_0
  - python-libarchive-c=2.8=py37_1004
  - pytz=2019.2=py_0
  - pywavelets=1.0.3=py37hd352d35_1
  - pyyaml=5.1.2=py37h516909a_0
  - pyzmq=18.1.0=py37h1768529_0
  - qt=5.9.7=h0c104cb_3
  - qtawesome=0.6.0=py_0
  - qtconsole=4.5.5=py_0
  - qtpy=1.9.0=py_0
  - r-askpass=1.1=r36hcdcec82_1
  - r-assertthat=0.2.1=r36h6115d3f_1
  - r-backports=1.1.4=r36hcdcec82_1
  - r-base=3.6.1=hba50c9b_4
  - r-base64enc=0.1_3=r36hcdcec82_1003
  - r-boot=1.3_23=r36h6115d3f_2
  - r-broom=0.5.2=r36h6115d3f_1
  - r-callr=3.3.2=r36h6115d3f_0
  - r-caret=6.0_84=r36hcdcec82_1
  - r-cellranger=1.1.0=r36h6115d3f_1002
  - r-class=7.3_15=r36hcdcec82_1001
  - r-cli=1.1.0=r36h6115d3f_2
  - r-clipr=0.7.0=r36h6115d3f_0
  - r-cluster=2.1.0=r36h9bbef5b_2
  - r-codetools=0.2_16=r36h6115d3f_1001
  - r-colorspace=1.4_1=r36hcdcec82_1
  - r-crayon=1.3.4=r36h6115d3f_1002
  - r-curl=4.2=r36hcdcec82_0
  - r-data.table=1.12.2=r36hcdcec82_1
  - r-dbi=1.0.0=r36h6115d3f_1002
  - r-dbplyr=1.4.2=r36h6115d3f_1
  - r-digest=0.6.21=r36h0357c0b_0
  - r-dplyr=0.8.3=r36h0357c0b_3
  - r-ellipsis=0.3.0=r36hcdcec82_0
  - r-essentials=3.6=r36_2001
  - r-evaluate=0.14=r36h6115d3f_1
  - r-fansi=0.4.0=r36hcdcec82_1001
  - r-forcats=0.4.0=r36h6115d3f_1
  - r-foreach=1.4.7=r36h6115d3f_0
  - r-foreign=0.8_72=r36hcdcec82_0
  - r-formatr=1.7=r36h6115d3f_1
  - r-fs=1.3.1=r36h0357c0b_1
  - r-generics=0.0.2=r36h6115d3f_1002
  - r-ggplot2=3.2.1=r36h6115d3f_0
  - r-gistr=0.4.2=r36h6115d3f_1002
  - r-glmnet=2.0_18=r36h9bbef5b_2
  - r-glue=1.3.1=r36hcdcec82_1
  - r-gower=0.2.1=r36hcdcec82_1
  - r-gtable=0.3.0=r36h6115d3f_2
  - r-haven=2.1.1=r36hde08347_2
  - r-hexbin=1.27.3=r36h9bbef5b_2
  - r-highr=0.8=r36h6115d3f_1
  - r-hms=0.5.1=r36h6115d3f_0
  - r-htmltools=0.3.6=r36he1b5a44_1003
  - r-htmlwidgets=1.3=r36h6115d3f_1001
  - r-httpuv=1.5.2=r36h0357c0b_1
  - r-httr=1.4.1=r36h6115d3f_1
  - r-ipred=0.9_9=r36hcdcec82_1
  - r-irdisplay=0.7=r36_1001
  - r-irkernel=1.0.2=r36h6115d3f_2
  - r-iterators=1.0.12=r36h6115d3f_0
  - r-jsonlite=1.6=r36hcdcec82_1001
  - r-kernsmooth=2.23_15=r36h9bbef5b_1004
  - r-knitr=1.25=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_1002
  - r-later=0.8.0=r36h0357c0b_2
  - r-lattice=0.20_38=r36hcdcec82_1002
  - r-lava=1.6.6=r36h6115d3f_0
  - r-lazyeval=0.2.2=r36hcdcec82_1
  - r-lifecycle=0.1.0=r36h6115d3f_0
  - r-lubridate=1.7.4=r36h0357c0b_1002
  - r-magrittr=1.5=r36h6115d3f_1002
  - r-maps=3.3.0=r36hcdcec82_1003
  - r-markdown=1.1=r36hcdcec82_0
  - r-mass=7.3_51.4=r36hcdcec82_1
  - r-matrix=1.2_17=r36hcdcec82_1
  - r-mgcv=1.8_29=r36hcdcec82_0
  - r-mime=0.7=r36hcdcec82_1
  - r-modelmetrics=1.2.2=r36h0357c0b_1
  - r-modelr=0.1.5=r36h6115d3f_0
  - r-munsell=0.5.0=r36h6115d3f_1002
  - r-nlme=3.1_141=r36h9bbef5b_1
  - r-nnet=7.3_12=r36hcdcec82_1003
  - r-numderiv=2016.8_1.1=r36h6115d3f_1
  - r-openssl=1.4.1=r36h9c8475f_0
  - r-pbdzmq=0.3_3=r36h559a7a4_1002
  - r-pillar=1.4.2=r36h6115d3f_2
  - r-pkgconfig=2.0.3=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_1002
  - r-plyr=1.8.4=r36h0357c0b_1003
  - r-prettyunits=1.0.2=r36h6115d3f_1002
  - r-processx=3.4.1=r36hcdcec82_0
  - r-prodlim=2018.04.18=r36h0357c0b_1003
  - r-progress=1.2.2=r36h6115d3f_1
  - r-promises=1.0.1=r36h0357c0b_1001
  - r-pryr=0.1.4=r36h0357c0b_1003
  - r-ps=1.3.0=r36hcdcec82_1001
  - r-purrr=0.3.2=r36hcdcec82_1
  - r-quantmod=0.4_15=r36h6115d3f_1
  - r-r6=2.4.0=r36h6115d3f_2
  - r-randomforest=4.6_14=r36h9bbef5b_1002
  - r-rbokeh=0.5.0=r36h6115d3f_1002
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1002
  - r-rcpp=1.0.2=r36h0357c0b_0
  - r-readr=1.3.1=r36h0357c0b_1002
  - r-readxl=1.3.1=r36h0357c0b_1
  - r-recipes=0.1.7=r36h6115d3f_0
  - r-recommended=3.6=r36_1003
  - r-rematch=1.0.1=r36h6115d3f_1002
  - r-repr=1.0.1=r36h6115d3f_1
  - r-reprex=0.3.0=r36h6115d3f_1
  - r-reshape2=1.4.3=r36h0357c0b_1004
  - r-rlang=0.4.0=r36hcdcec82_1
  - r-rmarkdown=1.15=r36h6115d3f_0
  - r-rpart=4.1_15=r36hcdcec82_1
  - r-rstudioapi=0.10=r36h6115d3f_2
  - r-rvest=0.3.4=r36h6115d3f_1
  - r-scales=1.0.0=r36h0357c0b_1002
  - r-selectr=0.4_1=r36h6115d3f_1001
  - r-shiny=1.3.2=r36h6115d3f_1
  - r-sourcetools=0.1.7=r36he1b5a44_1001
  - r-spatial=7.3_11=r36hcdcec82_1003
  - r-squarem=2017.10_1=r36h6115d3f_1002
  - r-stringi=1.4.3=r36h0e574ca_3
  - r-stringr=1.4.0=r36h6115d3f_1
  - r-survival=2.44_1.1=r36hcdcec82_1
  - r-sys=3.3=r36hcdcec82_0
  - r-tibble=2.1.3=r36hcdcec82_1
  - r-tidyr=1.0.0=r36h0357c0b_0
  - r-tidyselect=0.2.5=r36h0357c0b_1001
  - r-tidyverse=1.2.1=r36h6115d3f_1002
  - r-timedate=3043.102=r36h6115d3f_1001
  - r-tinytex=0.16=r36h6115d3f_0
  - r-ttr=0.23_5=r36hcdcec82_0
  - r-utf8=1.1.4=r36hcdcec82_1001
  - r-uuid=0.1_2=r36hcdcec82_1002
  - r-vctrs=0.2.0=r36hcdcec82_1
  - r-viridislite=0.3.0=r36h6115d3f_1002
  - r-whisker=0.4=r36h6115d3f_0
  - r-withr=2.1.2=r36h6115d3f_1001
  - r-xfun=0.9=r36h6115d3f_0
  - r-xml2=1.2.2=r36h0357c0b_0
  - r-xtable=1.8_4=r36h6115d3f_2
  - r-xts=0.11_2=r36hcdcec82_1
  - r-yaml=2.2.0=r36hcdcec82_1002
  - r-zeallot=0.1.0=r36h6115d3f_1001
  - r-zoo=1.8_6=r36hcdcec82_1
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - ripgrep=11.0.2=h516909a_3
  - rope=0.14.0=py_0
  - ruamel_yaml=0.15.71=py37h14c3975_1000
  - scikit-image=0.15.0=py37hb3f55d8_2
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.3.1=py37h921218d_2
  - seaborn=0.9.0=py_1
  - secretstorage=3.1.1=py37_0
  - sed=4.7=h1bed415_1000
  - send2trash=1.5.0=py_0
  - setuptools=41.2.0=py37_0
  - simplegeneric=0.8.1=py_1
  - singledispatch=3.4.0.3=py37_1000
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - snappy=1.1.7=he1b5a44_1002
  - snowballstemmer=1.9.1=py_0
  - sortedcollections=1.1.2=py_0
  - sortedcontainers=2.1.0=py_0
  - soupsieve=1.9.4=py37_0
  - sphinx=2.2.0=py_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sphinxcontrib-websupport=1.1.2=py_0
  - spyder=3.3.6=py37_0
  - spyder-kernels=0.5.2=py37_0
  - sqlalchemy=1.3.8=py37h516909a_0
  - sqlite=3.29.0=hcee41ef_1
  - statsmodels=0.10.1=py37hc1659b7_0
  - sympy=1.4=py37_0
  - tbb=2019.8=hfd86e86_0
  - tblib=1.4.0=py_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hed695b0_1003
  - tktable=2.10=h555a92e_2
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.2=py37_1000
  - traittypes=0.2.1=py_1
  - unicodecsv=0.14.1=py_1
  - unixodbc=2.3.7=h227dcee_1000
  - urllib3=1.25.6=py37_0
  - voila=0.1.17=py_0
  - voila-reveal=0.0.2=py_0
  - vtk=8.2.0=py37haa4764d_200
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - wurlitzer=1.0.3=py37_0
  - xlrd=1.2.0=py_0
  - xlsxwriter=1.2.1=py_0
  - xlwt=1.3.0=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.0=h3b9ef0a_0
prefix: /var/anaconda33
